2025-03-02 16:37:00,182 INFO    MainThread:3240 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_setup.py:_flush():67] Configure stats pid to 3240
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_setup.py:_flush():67] Loading settings from C:\Users\USER\.config\wandb\settings
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_setup.py:_flush():67] Loading settings from D:\AOIVietNam\PythonLearning\AOIBaiTap\wandb\settings
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:setup_run_log_directory():647] Logging user logs to D:\AOIVietNam\PythonLearning\AOIBaiTap\wandb\run-20250302_163700-jb6o04ap\logs\debug.log
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to D:\AOIVietNam\PythonLearning\AOIBaiTap\wandb\run-20250302_163700-jb6o04ap\logs\debug-internal.log
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:init():761] calling init triggers
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'epochs': 10, '_wandb': {}}
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:init():784] starting backend
2025-03-02 16:37:00,183 INFO    MainThread:3240 [wandb_init.py:init():788] sending inform_init request
2025-03-02 16:37:00,243 INFO    MainThread:3240 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-02 16:37:00,243 INFO    MainThread:3240 [wandb_init.py:init():803] backend started and connected
2025-03-02 16:37:00,244 INFO    MainThread:3240 [wandb_init.py:init():896] updated telemetry
2025-03-02 16:37:00,323 INFO    MainThread:3240 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 16:37:02,487 INFO    MainThread:3240 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 16:37:02,535 INFO    MainThread:3240 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 16:37:02,535 INFO    MainThread:3240 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 16:37:02,535 INFO    MainThread:3240 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 16:37:02,535 INFO    MainThread:3240 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 16:37:02,536 INFO    MainThread:3240 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 16:37:02,538 WARNING MsgRouterThr:3240 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 16:37:02,539 INFO    MsgRouterThr:3240 [mailbox.py:close():115] Closing mailbox, abandoning 3 handles.
